export const BUTTON_VARIANT_OUTLINED = 'outlined'
export const BUTTON_VARIANT_CONTAINED = 'contained'
export const TOGGLE_BUTTON_SHOW_PROJECTS = 'Show Projects'
export const TOGGLE_BUTTON_HIDE_PROJECTS = 'Hide Projects'
export const TOGGLE_BUTTON_LIGHT_MODE = 'Turn on Light Mode'
export const TOGGLE_BUTTON_DARK_MODE = 'Turn on Dark Mode'
export const EDITOR_DARK_MODE = 'vs-dark'
export const EDITOR_LIGHT_MODE = 'light'
