name: Check Version Match

on:
  pull_request:
    branches:
      - main

jobs:
  check_version_match:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get version from package.json
        id: package_json_version
        run: |
          package_json_version=$(jq -r '.version' package.json)
          echo "package_json_version=$package_json_version" >> $GITHUB_ENV

      - name: Get version from package-lock.json
        id: package_lock_version
        run: |
          package_lock_version=$(jq -r '.version' package-lock.json)
          echo "package_lock_version=$package_lock_version" >> $GITHUB_ENV

      - name: Compare versions
        run: |
          if [ "${{ env.package_json_version }}" != "${{ env.package_lock_version }}" ]; then
            echo "::error::Version mismatch: package.json (${{ env.package_json_version }}) and package-lock.json (${{ env.package_lock_version }}) versions do not match."
            exit 1
          else
            echo "Versions match: package.json and package-lock.json both have version ${{ env.package_json_version }}."
          fi
