name: Check Package Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Get current package version on main
        id: current-version
        run: |
          git fetch origin main:main
          current_version=$(jq -r '.version' <(git show main:package.json))
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Get package version on PR branch
        id: pr-version
        run: |
          pr_version=$(jq -r '.version' package.json)
          echo "pr_version=$pr_version" >> $GITHUB_ENV

      - name: Compare versions
        run: |
          if [ "${{ env.current_version }}" == "${{ env.pr_version }}" ]; then
            echo "Package version has not been updated."
            exit 1
          else
            echo "Package version has been updated."
          fi
