# .github/workflows/require-version-bump.yml
name: require version bump

on:
  pull_request:
    branches:
      - main

jobs:
  check_package_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify package.json update
        id: check_changes
        run: |
          # Check for changes in package.json
          if git diff --name-only HEAD HEAD~1 | grep -q 'package.json'; then
            echo "Package.json has been updated."
          else
            echo "::error::package.json has not been updated in this PR. Please update it before merging."
            exit 1
          fi
